# Generated by Django 4.2.3 on 2023-07-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_firs_name_customer_first_name_and_more'),
    ]

    operations = [
        
    ]
