# Generated by Django 4.2.3 on 2023-07-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_collection_description'),
    ]

    operations = [
        migrations.RunSQL("""
INSERT INTO store_collection(name)
VALUES('collection1')""","""
DELETE FROM store_collection WHERE name='collection1' """)
    ]
